#!/bin/bash

function help {
    echo 'gid adds, commits, and pushes your changes in a single command.'
    echo
    echo 'Usage: gid [directory]'
    echo 'cd to [directory] and git add/commit/pull/push everything all in one go.'
    echo
    echo 'Options:'
    echo '-b,--branch BRANCH            Set branch to be checked out. By default this is master.'
    echo '-f,--force                    Force push/pull any conflicting changes.'
    echo "-l,--lazy                     Set commit message to '$default_message.'"
    echo '-m,--message MESSAGE          Set MESSAGE as the git commit message.'
    echo '-r,--remote REMOTE            Push to REMOTE during git push. By default this is origin.'
}

function error {
    echo "$@" 1>&2
}

branch='master'
default_message='Automatically committed by gid'
directory='.'
force=''
message=''
remote='origin'

# Get options
while [ $# -gt 0 ]
do
    case "$1" in
        '-?'|-h|--help) # ? matches a single character by default, we don't want this behavior
        help
        exit 0
        ;;
        -b|--branch)
        branch="$2"
        shift
        ;;
        -f|--force)
        force='-f'
        ;;
        -l|--lazy)
        message="$default_message"
        ;;
        -m|--message)
        message="$2"
        shift
        ;;
        -r|--remote)
        remote="$2"
        shift
        ;;
        --) # Stop parsing
        shift
        directory="$@"
        break # From outer loop
        ;;
        *)
        directory="$1"
        ;;
    esac
    shift
done

cd "$directory" 2> /dev/null
if [ $? -ne 0 ]; then
    error "$directory does not exist."
    exit 1
fi

# Where the real work starts
git checkout $branch
if [ $? -ne 0 ]; then
    error "git checkout $branch failed."
    exit 2
fi

git add -A :/
if [ $? -ne 0 ]; then
    error 'git add -A :/ failed.'
    exit 3
fi

if [ -z "$message" ]; then
    git commit
    if [ $? -ne 0 ]; then
        error 'git commit failed.'
        exit 4
    fi
else
    git commit -m "$message"
    if [ $? -ne 0 ]; then
        error "git commit -m '$message' failed."
        exit 5
    fi
fi

git pull $force $remote $branch
if [ $? -ne 0 ]; then
    error "git pull $force $remote $branch failed."
    exit 6
fi

git push $force $remote $branch
if [ $? -ne 0 ]; then
    error "git push $force $remote $branch failed."
    exit 7
fi
